<!DOCTYPE html>
<!-- Template by html.am -->
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>${title}</title>
		<link rel="stylesheet" href="${baseUrl}public/asserts/css/style.css">
	</head>
	<body>
		<header id="header">
			<p>${header}</p>
		</header>
		<div id="container">		
			<main id="center" class="column">			
				${viewRender}
			</main>
			<nav id="left" class="column">
				<h3>Navigation</h3>
				<ul>
					<li><a href="${baseUrl}">Home</a></li>
					<li><a href="${baseUrl}users">Users</a></li>
					<li><a href="${baseUrl}users/true">Active Users</a></li>
					<li><a href="${baseUrl}users/form/create">Create User</a></li>
					<li><a href="${baseUrl}users/api">Users without template</a></li>
				</ul>
			</nav>
		</div>
		<div id="footer-wrapper">
			<footer id="footer">
				<p style="font-size: .875rem;">Examle from https://www.html.am</p>
			</footer>
		</div>
	</body>
</html>