name: PHP Linting
on: push
jobs:
  phpLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0
  phpcs:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: phpcs
        uses: shirobrak/action-phpcs@v1.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review  # Change reporter.
          phpcs_flags: '--standard=phpcs.xml src/'
