name: PHP Linting
on: push
jobs:
  phpLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0

      - name: PHP CS Fixer
        uses: StephaneBour/actions-php-cs-fixer@1.0
        with:
          dir: './src'